### ISSUE TITLE
Method to keep config files in sync

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#1]
Now that clusterware is intended to be installed on each node, we need a method to keep the customisable files in sync with a master copy, initially:

/opt/clusterware/etc/ipmi.conf
/opt/clusterware/etc/genders
/opt/clusterware/etc/modulespath

**Comment by mjtko** [comment]
Is `ipmi.conf` still in use in clusterware? I think that should be part of metalware now, i.e. `/opt/metalware/etc/ipmi.conf`?

**Comment by sierra-tango-echo** [comment]
No sorry, that one doesn't need to be synced. There are likely to be others though so I was thinking something where you could just specify paths of files that are needing to be copied from the master to the slaves?
