### ISSUE TITLE
consider restriction features on alces session

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#10]
When considering the use case for alces session as a potential simpler replacement for x2go/nx/vnc on login nodes, we came up with the following blockers:
- We'd need a way to restrict amount of sessions per machine per user to avoid them starting hundreds and locking up nodes
- We'd need a way to auto kill sessions after a default period, ideally users could also specify how long to hold the session open up to a max (default for both would be infinate to deal with ephemeral instances but both default and max would need to be configurable
- use a different address for the output message (on qdesktop we have a configurable 'domain' for a gethostip hook, so you can potential use an address that isn't associated to the default route)

**Comment by mjtko** [comment]
> use a different address for the output message (on qdesktop we have a configurable 'domain' for a gethostip hook, so you can potential use an address that isn't associated to the default route)

This is dealt with in acb172f -- adding entries to `/opt/clusterware/etc/mappingstab` will cause the session tool to supply a different address for the 'Host' field (for access) as well as retaining the existing address as 'Service host' (for reference/internal addressing purposes).  The format is as follows, where type should be `access`.  (This is a generic feature which we can reuse for any types of mappings, but this is the first type implemented!)

```
#source    type      mapping
10.0.0.47  access    192.168.44.47
```

**Comment by mjtko** [comment]
The above commits address configuration/application of max sessions per machine (currently by a single configuration variable that restricts all users to having a maximum number of sessions on the node) as well as maximum runtimes/default runtimes/auto killing of sessions after a period of time, with warnings.
