### ISSUE TITLE
Alces session run via a scheduler

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#11]
We could consider using alces session for general interactive access on node slots (replace qdesktop), but it seems at the moment if you alces session from a qrsh session, alces sessions are not killed on termination of the scheduler job - maybe this is something we should consider making work in some way as an enhancement?

**Comment by mjtko** [comment]
Previously we've done this by waiting on the session in the foreground and waiting for cleanup signals from the scheduler which we use to cleanup/kill:

```
cleanup () {
  echo "Cleaning"
  kill -TERM $VPID
}

trap "cleanup" SIGUSR2 SIGUSR1

echo "Starting"
setsid run-desktop -fg &
VPID=$!
echo $VPID
while [ -d /proc/$VPID ]; do
  sleep 5 &
  wait
done
echo "Completed."
```

We could probably do a similar thing with the clusterware sessions with this kind of recipe:

```
cleanup () {
  echo "Cleaning"
  alces session kill $SESSIONID
}

trap "cleanup" SIGUSR2 SIGUSR1
SESSIONID=$(alces session start --terse default)
alces session wait $SESSIONID
```

**Comment by mjtko** [comment]
After discussion:

We should update the `qdesktop` command to use `alces session` as the underlying session orchestrator and ship it along with our GridScheduler serviceware.

While this doesn't address the problem of running `alces session` under `qrsh` and then logging out (which, like any other process that is placed in the background under qrsh, leaves it running), it fulfils the core requirement of consistency when launching desktops within the compute estate.  A possible future enhancement to fix this would be to prevent `alces session` from being run directly on nodes.

**Comment by mjtko** [comment]
This now exists in the GridScheduler serviceware.
