### ISSUE TITLE
new node customisation script

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#113]
It may be worth looking at adding functionality to clusterware to provide a simple 'run on launch' script. A simple use case is that a customer wants a yum package installed on each compute node, but as the nodes are scaling up and down, they can't simply use pdsh whilst all nodes are up. 
Something very basic which picks up a script from the login node and is potentially passed some arguments about the node to run at a late stage in the boot process. 

More advanced customisation can be done by building configuration management into the base image itself, but a v basic option i think is worth considering for clusterware.

**Comment by mjtko** [comment]
Possibly superceded by alces-software/clusterware-handlers#25 but may be different because controlled by master node rather than by content within image.
