### ISSUE TITLE
q left in disabled state

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#122]
[alces@login1(munchkin1) ~]$ qstat -f
## byslot.q@ip-10-75-0-206.eu-wes BIP   0/0/2          0.01     linux-x64     d

bynode.q@ip-10-75-0-206.eu-wes IP    0/0/1          0.01     linux-x64     d
###### 
- PENDING JOBS - PENDING JOBS - PENDING JOBS - PENDING JOBS - PENDING JOBS
  ############################################################################
    1 11.15234 STDIN      alces        qw    05/04/2016 12:12:34     1
    2 6.02734 STDIN      alces        qw    05/04/2016 12:12:35     1
    3 4.36068 STDIN      alces        qw    05/04/2016 12:12:35     1
    4 3.40234 STDIN      alces        qw    05/04/2016 12:12:36     1

**Comment by mjtko** [comment]
Caused by not being able to shoot a viable node due to ASG having minimum.  Queues aren't reenabled under this condition.
