### ISSUE TITLE
s3cmd as serviceware

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#126]
We have aws tools as serviceware exposed as a module, s3cmd is another one people will expect to be there so maybe we should expose it as a module, Alternatively we could just install the epel version to the image?

**Comment by sierra-tango-echo** [comment]
aware that alces storage provides extra functionality on top of s3cmd, this is just to stop the initial 'this is missing' complaints

**Comment by mjtko** [comment]
This issue was moved to alces-software/clusterware-services#21
