### ISSUE TITLE
Allow manual kick-off of customiser

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#143]
It would be useful if it was possible to manually start the customiser - there are a few different reasons/use-cases for this; 
1. On creation of an accounts first Flight cluster - the customiser bucket hasn't yet been created or populated, but a user may still wish to run customisation scripts through the tool rather than other means
2. A user may not require the use of the customiser tool on cluster 1, 2 or 3 - but on cluster 4 may require some level of customisation on each of the nodes for (insert something a user might do here). At this point, it would be useful to be able to dump customisation scripts in the bucket, and manually fire off the tool

**Comment by mjtko** [comment]
For the first part of (2):

The customizer scripts are passed the cluster name so they could branch on that to decide if customizations are to be applied.  For more complicated setups, it could branch on other variables available from Clusterware, such as what tags are set via `config.yml`.  There is rudimentary functionality for selecting a "personality" for a cluster (currently hard-coded to `default`).

I think this shakes down into features like this:
1. Allow specification of a customization personality via `config.yml`. Possibly multiple personalities, so additional behaviours can be layered.
2. Create a tool to resync customization scripts from the bucket
3. Allow the superuser to manually invoke (on one or more nodes):
   1. life-cycle event(s)
   2. `member-join` events for all current members
