### ISSUE TITLE
Ensure `gridware install` in binary mode fails when it should

### ISSUE THREAD

**Issue by mjtko** [alces-software/clusterware#162]
A situation can occur where not all requirements are imported before proceeding with import.

An example of this was is here:

https://travis-ci.org/alces-software/gridware-packages-main/jobs/131773139

See `khmer` variant `python34` (which at the time had a slightly broken runtime dependency on a `python3` variant of `screed`).

**Comment by bobwhitelock** [comment]
This issue was moved to alces-software/gridware#7
