### ISSUE TITLE
Option to disable hyperthreaded cores on instances when launched

### ISSUE THREAD

**Issue by wdm78** [alces-software/clusterware#164]
We need an option to disable hyperthreaded cores on an instance, ideally before the job-scheduler tries to detect how many cores an instance has. This would be useful on both AWS and OpenStack environments. 

N.B. No immediate requirement - but I'm expecting someone to ask for this at some point.

Jeff from AWS shared this script with us that I've tested working on AWS c4 instances:
https://cfncluster-public-scripts.s3.amazonaws.com/disable_hyperthreading

**Comment by mjtko** [comment]
@wdm78: I’ve implemented a mechanism for disabling/enabling hyperthreading via `alces configure hyperthreading <disable|enable>`.  Do you think we should disable hyperthreading by default or leave it on by default?

**Comment by wdm78** [comment]
Great - let's leave hyperthreading on by default

**Comment by mjtko** [comment]
Ok -- at the moment hyperthreading is not affected at boot unless a value exists in the `config.yml` (or `defaults.yml`) instructing it to be explicitly enabled or disabled.  As our templates don't supply this value and our images don't contain it in the defaults it'll remain for HT-capable instances.

We can modify `defaults.yml` in our images later if we want to change the default behaviour without changing the CFN templates.
