### ISSUE TITLE
Warning when multiple identical Gridware packages installed

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#169]
If multiple identical versions of Gridware packages are installed (i.e. in `local` and other pulled in depots), the following warning occurs: 

```
  cmdVersion.c(692):WARN:156: Duplicate alias 'mpi-openmpi' found
---  /opt/gridware/bioinformatics/el7/etc/modules  ---
  cmdVersion.c(692):WARN:156: Duplicate alias 'mpi-openmpi' found
  cmdVersion.c(692):WARN:156: Duplicate alias 'mpi-openmpi' found
  apps/bamtools/2.3.0/gcc-4.8.5
  apps/bcftools/1.3/gcc-4.8.5
```

Whilst it's not at all a problem - it might be nice to silence that somehow?

**Comment by mjtko** [comment]
Adding `module-log warn null` a the top of `~/.modulerc` seems to do it.
