### ISSUE TITLE
clusterware Howto& Template tools

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#17]
Wrap up the old 'howto' and 'template' tools into clusterware. These would need to be some sort of tool that displays a default set of content, but allows that content to be edited and added to locally. 
See current cluster for examples, but eg:
HOWTO shows basic text pieces for various cluster activities:
eg:
alces howto list
1 - localizing files
2 - running interactive desktop jobs
3 - running non-interactive batch jobs through the scheduler

alces howto show 1

TEMPLATE allows download of a example job submission template, for the specific environment, again most likely a standard version can be fetched and modified to suit the environment.
eg:
alces template list
alces template get 3 myjob.sh

**Comment by mjtko** [comment]
Both `howto` and `template` actions have now been implemented.
