### ISSUE TITLE
Viewing storage configurations setup with alces storage command

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#203]
_From @wdm78 on May 15, 2016 16:11_

It would be useful to be able to see the names of storage configurations setup by users with the `alces storage configure` command.

_Copied from original issue: alces-software/flight-aws-marketplace#47_

**Comment by vlj91** [comment]
_From @mjtko on August 10, 2016 20:16_

What’s the use case here? Users can see what they have set up by using `alces storage avail` — is this for admin use?

**Comment by vlj91** [comment]
_From @wdm78 on August 11, 2016 10:20_

I think I was getting confused about what `alces storage avail` displays - ideally, I'd like a way to see both what storage areas are setup, and what storage types are enabled. I think `alces storage avail` is doing the former, when I'd wrongly assumed it was doing the latter. This issue should probably be about how to list what storage back-ends are enabled (or available to be enabled).

**Comment by vlj91** [comment]
_From @mjtko on August 11, 2016 10:24_

If you want to see what backends are available, you can do this:

```
[vagrant@login-2bf7dc3(el7cluster) ~]$ al sto avail --backends
[ ] base/dropbox
[*] base/posix
[*] base/s3
```

Do we need both in one view? Maybe it's a bit confusing to have both behaviours under one command?

**Comment by vlj91** [comment]
_From @mjtko on August 11, 2016 10:25_

Perhaps `avail` for backends and `show` to show the configured storage areas?

**Comment by vlj91** [comment]
Moving to clusterware as it is more appropriate there

**Comment by bobwhitelock** [comment]
@mjtko - to confirm, is this what we want to do for this issue:

> `avail` for backends and `show` to show the configured storage areas

So the new `alces storage avail` should display what is currently the output for `alces storage avail --backends`, and the new `alces storage show` should display the current output for `alces storage avail`?

**Comment by mjtko** [comment]
Yup! Confirmed!

**Comment by bobwhitelock** [comment]
Do you think it would be more consistent to call the new action `list`/`ls` rather than `show`? This would be consistent with the usage in `alces session` and `alces module` of `avail` and `list`, as well as prevent an inconsistency with `alces template show` which shows a single template rather than list the current ones (which is `alces template list`).

**Comment by bobwhitelock** [comment]
On second thoughts, having learnt to read, I notice we already have an `alces storage list` action for another purpose, so I'll stick to the original plan!
