### ISSUE TITLE
Allow certain packages within a depot to be imported as binary

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#204]
Depots can be installed either with all packages compiled from source, or all packages imported from pre-packaged binaries. There are cases (particularly where a depot may include `atlas`) that you may wish to import certain packages in a depot as a binary. Perhaps we could add an option to `depot install` that allows us to flag certain packages to be imported as a binary when the `--compile` option is provided, something along the lines of:

```
`alces gridware depot --compile --binary libs/atlas/3.10.2 install benchmark`
```

Bonus points for working the other way round (install all from binaries but compile certain packages).

**Comment by bobwhitelock** [comment]
This issue was moved to alces-software/gridware#6
