### ISSUE TITLE
`alces customize pull` displays errors for each customization/feature pulled

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#207]
For each customization/feature pulled - the following error/warning is displayed, although this does not (seemingly) affect anything

```
Retrieving feature customizations from: alces-flight-profiles-eu-west-1/features/slurm
ERROR: Parameter problem: Expecting S3 URI with just the bucket name set instead of 's3://alces-flight-profiles-eu-west-1/features/slurm/'
```

**Comment by mjtko** [comment]
This is happening due to the change to create the customization bucket if it doesn't exist.  Fixing it should be relatively easy.

**Comment by mjtko** [comment]
Fixed in https://github.com/alces-software/clusterware-handlers/commit/cd0af9339d3a78a86ac74e16c495503160810dc4
