### ISSUE TITLE
`alces gridware depot disable <depot>` should not leave modules loaded

### ISSUE THREAD

**Issue by benarmston** [alces-software/clusterware#208]
Consider there is a depot, say my_depot, containing a package, say my_package.  The depot has been enabled (`alces gridware depot enable my_depot`) and the package loaded (`alces module load apps/my_package`).

Currently, disabling the depot leaves the package loaded.  This could cause some confusion for a user who may be looking in `alces module avail` trying to figure out where that loaded package comes from.

When disabling a depot with loaded packages we should inform the user that the depot has loaded packages and prompt them for instructions on what to do.  Valid options that spring to mind include, 1) leaving them loaded; 2) unloading them all; 3) aborting the disable depot operation.

**Comment by bobwhitelock** [comment]
This issue was moved to alces-software/gridware#5
