### ISSUE TITLE
Ctrl-C while synchronizing can cause spinner to repeat in shell until end of session

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/clusterware#219]
If I Ctrl-C on initial login while `Synchronizing directory '/home/alces'...` is running, the spinner displaying the progress of this can continue to be printed over the current text in the terminal, overwriting anything else I input, until I log out and in again.

**Comment by BobWhitelock** [comment]
This issue was moved to alces-software/gridware#2

**Comment by bobwhitelock** [comment]
Whoops, accidentally closed.

**Comment by WilliamMcCumstie** [comment]
So the bug has something to do with

**Comment by WilliamMcCumstie** [comment]
Whoops accidentally closed it as well. 

The bug has something to do with: `/opt/clusterware/libexec/sync/actions/pull` as part of the `_pull` method.

I believe what is happening is the spinner is started with the `doing` command but the script exists with `ctrl-c` before the `say_done` command is called. This prevents the spinner from exiting.

**Comment by mjtko** [comment]
This might be a case of setting a `trap` for the INT signal that always stops the spinner if it's running.
