### ISSUE TITLE
Don't allow alces gridware init as non-root 

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/clusterware#224]
Seems that runnning `alces gridware init` will cause all sorts of unexpected breakage and errors if run as a non-root user (i.e. alces).

**Comment by WilliamMcCumstie** [comment]
This looks to be fixed. Running `alces gridware init` as non root user now produces:
```
alces gridware: permission denied
```

**Comment by mjtko** [comment]
Not sure it is fixed; latest RC (as `alces`):

```
[alces@login1(markt-solo2) ~]$ alces gridware init foo

 > Performing initial configuration for 'local' depot
       Configure ... OK

 > Setting up depot structure for 'el7' in 'local'
       Configure ... OK

 > Setting up local package repository
       Configure ... OK

 > Setting up local depot repository
       Configure ... OK
```

**Comment by WilliamMcCumstie** [comment]
So done some digging and user either has to be running it as `sudo` or part of the `gridware` group.

So looks like we need to `process_rexec_sudo` if we are running as `non-root` user and remove the check on the `gridware` group.

I'm not sure if their are non-root `gridware-group` users however as this will prevent them from running `alces gridware init`.

@mjtko any ideas?

**Comment by mjtko** [comment]
I think we simply choose to always `process_reexec_sudo` for this action.
