### ISSUE TITLE
'Clusterware release' version number blank on web front end

### ISSUE THREAD

**Issue by ColonelPanics** [alces-software/clusterware#230]
With the latest professional S3 template, the flight web page doesn’t show any version number for 'Clusterware release' at the bottom of the page (beneath 'Cluster name')

<img width="208" alt="screen shot 2017-04-26 at 17 36 05" src="https://cloud.githubusercontent.com/assets/27725639/25445661/dfb970a0-2aa6-11e7-82f1-38065fc0f634.png">

**Comment by mjtko** [comment]
Fixed in https://github.com/alces-software/clusterware-handlers/commit/1ec99923bb3531207113e2884ecfa12702376efe
