### ISSUE TITLE
Windows VPN config file does not have .ovpn extension

### ISSUE THREAD

**Issue by ColonelPanics** [alces-software/clusterware#231]
The VPN client config for Windows is provided as a .conf file but needs to be .ovpn for OpenVPN to use it. Renaming the file to .ovpn does lead to OpenVPN seeing the configuration.

**Comment by mjtko** [comment]
Fixed in https://github.com/alces-software/clusterware-handlers/commit/aceefcf759eb4e56a794ade28095e83cd13c98ae
