### ISSUE TITLE
Intermittent Customize Failure ($cw_ROOT/etc/cluster-customizer/config.yml missing)

### ISSUE THREAD

**Issue by ColonelPanics** [alces-software/clusterware#236]
## Description

Intermittently, when a new flight instance is created the `alces customize apply` command does not work on compute nodes - this is due to `/opt/clusterware/etc/cluster-customizer/config.yml` not being present (for compute nodes, login node has file).

It has been speculated that the compute node's `curl` to pull the config is occasionally running before the HTTP server on the login node is up.

@mjtko comment on issue:
> to me it looks like a network connectivity problem
so, probably no connectivity to the master node available when the `curl` is executed
maybe we should include a `_wait_for_master` function.

## Steps to Reproduce

**This issue cannot be reproduced reliably, it happens occasionally with CloudFormation or `fly-dev` created clusters (1 in 4 instances)**

- Fly command used in all attempts to replicate

```
fly-dev cluster launch --solo --key-pair aws_ireland --runtime 540 --parameter-directory ~/FlyParams stu-customize-test-fly
```

- See [CloudFormationParameters.txt](https://github.com/alces-software/clusterware/files/1000512/CloudFormationParameters.txt) for additional CloudFormation info when attempting to replicate

## Logs / Output

```
[alces@flight-214(stu-customize-test-fly-3) ~]$ alces customize avail
-e:1:in `eval': No such file or directory @ rb_sysopen - /opt/clusterware/etc/cluster-customizer/config.yml (Errno::ENOENT)
	from /opt/clusterware/opt/ruby/lib/ruby/2.2.0/psych.rb:464:in `open'
	from /opt/clusterware/opt/ruby/lib/ruby/2.2.0/psych.rb:464:in `load_file'
	from (eval):2:in `<main>'
	from -e:1:in `eval'
	from -e:1:in `<main>'
```

- `/var/log/clusterware/instance.log` from failing `fly-dev` instance

```
[cluster-customizer:initialize] /opt/clusterware/etc/config.yml does not yet exist, waiting 10 seconds then trying again [2 remaining]
[cluster-customizer:initialize] Retrieving customizer configuration from http://10.75.128.90/customizer/config.yml
[cluster-customizer:initialize] Retrieving customizer configuration failed.
[cluster-customizer:initialize]   >>> Loaded plugins: fastestmirror
```

- `/var/log/clusterware/instance.log` from working `fly-dev` instance

```
[cluster-customizer:initialize] /opt/clusterware/etc/config.yml does not yet exist, waiting 10 seconds then trying again [2 remaining]
[cluster-customizer:initialize] Retrieving customizer configuration from http://10.75.128.117/customizer/config.yml
[cluster-customizer:initialize]   >>> Loaded plugins: fastestmirror
```

## Workaround

This issue can currently be worked around by manually running the following command (from the compute node)
```
sudo curl -Lsf -o "/opt/clusterware/etc/cluster-customizer/config.yml" "http://<headnode_ip>/customizer/config.yml"
```

## Notes

- Version 0.6.0 of `fly-dev` used
- Default `solo.yml` file used with `fly-dev`
- [Community template rc7](https://s3-eu-west-1.amazonaws.com/alces-flight/Templates/awsmp/2017.1rc7/awsmp.solo-community.json) used for CloudFormation
- This only effects the compute node which comes up at creation, any nodes brought up (via autoscaling) will have `/opt/clusterware/cluster-customizer/config.yml`

**Comment by mjtko** [comment]
While we had implemented a `_wait_for_master` check, it was only waiting until the master node was pingable rather than when port 80 was available.  Working theory is that the master would indeed have been pingable but not yet fully configured.  The commit above makes the slave node wait until port 80 is accessible as well as waiting for up to 200s rather than the previous 30s.
