### ISSUE TITLE
Missing help for `alces service`

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/clusterware#239]
Some of the commands in `alces service` do not have corresponding help. The autocomplete is working correctly (see below) however `build` and `package` do not have help. 

```
[vagrant@login-3753735(el7cluster) ~]$ alces service 
avail    build    enable   help     install  package  update  
```

```
alces service help build 
alces service help: no such topic: build

  NAME:

    alces service

  DESCRIPTION:

    Install and manage serviceware.

  COMMANDS:

    alces service help      More help about this command.
    alces service avail     List installed/available serviceware.
    alces service enable    Enable a serviceware component.
    alces service install   Install serviceware from a repository.
    alces service update    Update serviceware repository.
```

**Comment by mjtko** [comment]
The `build` and `package` actions aren't really meant to be user-facing -- they're helpers that allow us to (re)build and tar up serviceware when we create/update it.  Probably could do with being removed from the autocomplete so they don't end up confusing users.
