### ISSUE TITLE
Flight VPN Web - 403 Forbidden

### ISSUE THREAD

**Issue by ColonelPanics** [alces-software/clusterware#251]
On a 2017.2 instance, the VPN configuration is show as:
```
[alces@login1(mycluster) ~]$ alces about vpn
   VPN configuration path: /opt/clusterware/etc/openvpn/client/clusterware
     Tarred configuration: /opt/clusterware/etc/openvpn/client/clusterware-openvpn.tgz
     Zipped configuration: /opt/clusterware/etc/openvpn/client/clusterware-openvpn.zip
Tunnelblick configuration: /opt/clusterware/etc/openvpn/client/clusterware-tunnelblick.zip
        Download web page: https://mycluster-9a9ac994.cloud.alces.network/vpn/
 Download access username: vpn
 Download access password: xMPZyI7Yx0
```

If I try to visit https://mycluster-9a9ac994.cloud.alces.network/vpn/ I end up hitting a `403 Forbidden` page, however, changing to the URL https://mycluster-9a9ac994.cloud.alces.network redirects to https://launch.alces-flight.com/cluster/mycluster-9a9ac994.cloud.alces.network which I believe is the expected behaviour.

Depending on how the Flight Launch dashboard is going to work, it may just require dropping `/vpn/` from `Download web page` in `alces about vpn`.

**Comment by mjtko** [comment]
@benarmston: can you take a look at this and comment please?

**Comment by benarmston** [comment]
@ColonelPanicks could you provide reproduction steps please?  I'd like to make sure that I'm using the same AMI / template set as the one you used.

**Comment by benarmston** [comment]
@ColonelPanicks I've been able to reproduce, and I understand your issue now.

**Comment by ColonelPanics** [comment]
@benarmston okay, just about to post extra info! LMK if there's anything I can do on my end

**Comment by benarmston** [comment]
@ColonelPanicks could you take a look at `light-wildcat-usb-drive` IP `34.236.183.180` and see if that behaves as you expect.

**Comment by ColonelPanics** [comment]
@benarmston looks to be working as expected!

**Comment by benarmston** [comment]
@ColonelPanicks awesome.

@mjtko I've committed a fix for this issue at https://github.com/alces-software/clusterware-handlers/commit/aa07d626c056a554d4495d48bba1f4175f9c2e69.  You've spoken about a feature that can patch clusters when they start.  Is this fix a candidate for that?  If so, would you like to provide me with instructions on how to accomplish that.

**Comment by mjtko** [comment]
As we're still in prerelease, this fix can be merged through to the `develop` branch.

**Comment by benarmston** [comment]
The fix has been merged to the develop branch of clusterware-handlers.
