### ISSUE TITLE
Compute node memory limits

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#30]
The AlcesHPC puppet modules used to set ulimits typical for compute type jobs, we don't do this with clusterware - I'm not sure if this should be something we do with the image or with clusterware (at least the SGE EL7 change below will need to be clusterware at least I think...) maybe needs more discussion about where it should go - but logging here anyway

Before the limits:

```
[alces-cluster@headnode1(edi-build) ~]$ echo 'ulimit -l' | qsub -q *@node2i01
Your job 21 ("STDIN") has been submitted
[alces-cluster@headnode1(edi-build) ~]$ cat STDIN.o21
64
```

After on EL7 with the both below patches:

```
[alces-cluster@headnode1(edi-build) ~]$ echo "ulimit -l" | qsub -q *@node2i01
Your job 29 ("STDIN") has been submitted
[alces-cluster@headnode1(edi-build) ~]$ cat STDIN.o29
unlimited
```

EL6 + EL7 for (qrsh):

```
cat << EOF > /etc/security/limits.d/99-clusterware.conf
#Allow all users to lock all memory
* soft memlock unlimited
* hard memlock unlimited
EOF
```

EL7:
Add:

```
LimitMEMLOCK=infinity
```

to the [service] section of /etc/systemd/system/clusterware-gridscheduler-execd.service

**Comment by mjtko** [comment]
Yup, I think this should go in Clusterware (specifically in the Serviceware for GridScheduler).  Is there an equivalent for `LimitMEMLOCK=infinity` that needs adding the the EL6 SysV init script -- perhaps a `ulimit` command?

**Comment by sierra-tango-echo** [comment]
I looked at the time and it didn't seem to have one in el6 I guess because the init.d script sourced the limits.d somehow so picked it up from there

**Comment by mjtko** [comment]
Ok, will add to Serviceware. Thanks.

**Comment by mjtko** [comment]
This issue was moved to alces-software/clusterware-services#5
