### ISSUE TITLE
Userdata route53 control

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#32]
after installing the aws handler route53 timeouts start happening on the slave nodes, which if you don't have a route53 zone setup makes things take longer, can we have a way to force skip the timeouts by doing something in the userdata?

**Comment by mjtko** [comment]
This issue was moved to alces-software/clusterware-handlers#9

**Comment by mjtko** [comment]
This relates to the `clusterable-aws-compat` handler, so moved to alces-software/clusterware-handlers repo.

**Comment by mjtko** [comment]
Omitting the `aws_zone_name` key from the userdata-generated config file will cause all route53 lookups/creations to be skipped.
