### ISSUE TITLE
EL7 Gridware Depot: Benchmark

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#37]
Build el7 depot `benchmark` with: 

hpcc 1.4.1
hpl 2.1
iozone 3.420
memtester 4.3.0
openmpi 1.8.5

Need to build atlas in a generic way that we can link HPL/HPCC against it.

**Comment by mjtko** [comment]
There is now an option to build ATLAS generically.  Install the 3.10.2 package with `cpuspeed=generic` to trigger the build of a generic ATLAS.

**Comment by vlj91** [comment]
Benchmark depot now has all of the above
