### ISSUE TITLE
Lightweight session type

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#40]
We should look into either: 
- an additional, lightweight desktop session type, with fewer required packages than the gnome desktop group to reduce overall image size
- look at installing only the required gnome packages - rather than everything included in the current groupinstall

**Comment by mjtko** [comment]
The smallest GNOME desktop I could get going is this for EL7:

```
    yum -e0 -y update
    yum -e0 -y groupinstall 'X Window System' 'Fonts' 'GNOME'
    yum -e0 -y install evince
    yum -e0 -y remove gnome-packagegit
```

And this for EL6:

```
    yum -e0 -y update
    yum -e0 -y groupinstall 'X Window System' 'Fonts' 'Desktop' 'Desktop Platform'
    yum -e0 -y install evince
    yum -e0 -y remove gnome-packagegit
```

I'm not sure there's a more minimal GNOME variant we can do, but perhaps we can roll an XFCE desktop (or, at a pinch LXDE from somewhere?).  XFCE looks reasonably easy to accomplish as it is available in EPEL:

http://unix.stackexchange.com/questions/181503/how-to-install-desktop-environments-on-centos-7
http://sharadchhetri.com/2014/01/09/install-xfce-desktop-minimal-installed-centos-6-x/

**Comment by mjtko** [comment]
This issue was moved to alces-software/clusterware-sessions#2
