### ISSUE TITLE
More advanced Depot selection

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#42]
Depots are already getting large and unwieldy, going forward we could look into:
- separate content tarballs for each distribution
- choose individual pre-built packages from a depot

**Comment by mjtko** [comment]
As per above commits:
- distro specific depot content is tried first (allowing us to split depots by distro)
- prebuilt binaries can be imported/exported using `import`/`export` commands

It may be worth extending the latter to allow 'groups' to be imported which would be a little like a depot, but more selective.

**Comment by mjtko** [comment]
Another idea related to this: install an entire depot from source (i.e. compile optimally for particular platform). Could use the groups as above.

**Comment by mjtko** [comment]
Further concepts:
- Depots should be retrievable from a 'depot repot' (i.e. add configuration to point to metadata that describes what depots can be installed).
- Depots should be exportable by a "curator" (including distro dependencies)
