### ISSUE TITLE
Initialise a new gridware repository

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#43]
Currently when creating a new gridware repository (ie mounting a clean NFS share on /opt/gridware) we have to copy the contents that was created by the clusterware installer from the old /opt/gridware to the new one. Is it possible to add the process of initialising an empty gridware repository as a clusterware command rather than part of the install process in order to make commissioning an application appliance a simpler process?

**Comment by mjtko** [comment]
The Gridware tree is no longer initialized as part of the install process.  Instead, it should be initialized using the `alces gridware init` command.  This defaults to initializing the tree in the location specified in `/opt/clusterware/etc/gridware.rc`, which defaults to `/opt/gridware`.

If the Gridware tree has not been initialized then the `alces gridware` command will refuse to run any command other than `alces gridware init`.
