### ISSUE TITLE
Gridware search

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#44]
We should look to implement a search tool to `alces gridware`, i.e. `alces gridware search python`

**Comment by mjtko** [comment]
This can be done with `alces gridware list` which accepts a glob to search for, e.g.:

```
[root@master-29d4fee(el7cluster) build]# alces gridware list python
base/apps/python/2.7.3  base/apps/python/2.7.5  base/apps/python/2.7.8

[root@master-29d4fee(el7cluster) build]# alces gridware list python*
base/apps/python/2.7.3   base/apps/python/2.7.5   base/apps/python/2.7.8   base/apps/python3/3.2.3
base/apps/python3/3.3.3  base/apps/python3/3.4.0  base/apps/python3/3.4.3

[root@master-29d4fee(el7cluster) build]# alces gridware list *python*
base/apps/ipython/2.3.0   base/apps/python/2.7.3    base/apps/python/2.7.5    base/apps/python/2.7.8
base/apps/python3/3.2.3   base/apps/python3/3.3.3   base/apps/python3/3.4.0   base/apps/python3/3.4.3
base/libs/biopython/1.61  base/libs/biopython/1.63
```

Will leave this open for catching any suggestions and/or additional use cases that come up though.

**Comment by mjtko** [comment]
Now has `alces gridware search` which will do a string search through package path (name), description, summary and group (or selectively one or more of name, group and description+summary).

@vlj91 Does that do the trick for you? :)

**Comment by mjtko** [comment]
Closing this -- reopen further tickets if search needs improving or new use cases arise.
