### ISSUE TITLE
Symphony puppet handler/hooks

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#50]
To integrate better with symphony, implement a process that installs the puppet client from the symphony director and setups puppet to run, this will allow for easier site customisation of semi-ephemeral clusters. 

Details on what exactly needs to be run to follow..

**Comment by mjtko** [comment]
After discussion, we're planning to implement this using HTTP trigger hooks/scripts on an appropriate appliance rather than directly as Clusterware hooks.
