### ISSUE TITLE
Error messages after deleting jobs

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#7]
After running 'kill' on some sessions, im getting the following for the killed sessions..

[alces-cluster@node003(***) ~]$ alces session list
+----------+---------+------+----------+-------------------------------------------------------+
| Identity | Display | Port | Password | URL                                                   |
+----------+---------+------+----------+-------------------------------------------------------+
/opt/clusterware/libexec/session/actions/list: line 44: /users/alces-cluster/.cache/clusterware/sessions/5609308e-7b48-11e5-922d-5065f365c162/metadata.vars.sh: No such file or directory
| 5609308e |       : |  |  | vnc://alces-cluster:@:                                |
/opt/clusterware/libexec/session/actions/list: line 44: /users/alces-cluster/.cache/clusterware/sessions/d8109f04-7b48-11e5-8945-5065f365c162/metadata.vars.sh: No such file or directory
| d8109f04 |       : |  |  | vnc://alces-cluster:@:                                |

**Comment by mjtko** [comment]
Discussion regarding this: https://alces.slack.com/archives/clusterware/p1445870083000165

Root cause: `pgrep` in EL6 exits with 0 even if it can't read the pidfile/the pidfile doesn't exist.  Yay. :clap:

**Comment by mjtko** [comment]
A further bug related to this issue was fixed in d2e20e3df2c23617e5b154dba46677ba41d82041 -- prior to this is was possible that all but the latest spawned service were not correctly terminated when the session was killed (specifically, websockify was being left lying around).
