### ISSUE TITLE
Remove the extra configure in alces configure

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#83]
When running `alces configure`, the file write stage message has two `configure`s in: 

```
[alces@login1(unconfigured) ~]$ alces configure
Cluster name [mycluster]: moose
Cluster UUID [e0028316-6377-45c1-834a-f4c95a178a86]:
Cluster secret [kwLBj6IMGgX228t92oWb]:
Master node IP address [<none>]:
Node role [master]:
alces configure configure: configuration written to /opt/clusterware/etc/config.yml
```

**Comment by mjtko** [comment]
Easier said than done -- all the other clusterware actions are: `alces <tool> <action>`.  I special-cased alces configure to redirect `alces configure` -> `alces configure configure`. :)

We might need to come up with a different tool name.  Maybe `alces node configure`?  And then we could move `alces about node` (the only current `about` action) to `alces node info` or something?

**Comment by vlj91** [comment]
`alces node configure` sounds good - if it isn't too much trouble! And the latter suggestion would also make sense keeping it in the same "tool"
