### ISSUE TITLE
Deal with additional storage volumes

### ISSUE THREAD

**Issue by vlj91** [alces-software/clusterware#90]
It would be useful, if possible to either have a new handler or modify one of the existing ones to deal with mounting, formatting and sharing additional volumes throughout the environment. Currently we are doing so by just adding the commands to run in cloudinit, which is a bit unpleasant.

**Comment by mjtko** [comment]
@vlj91: can you expand on what you would like the handler to do please, or provide examples of what we’re currently doing that could be better encapsulated in a handler?

**Comment by sierra-tango-echo** [comment]
I think we've re-thought this now so its possibly even less of an issue. We probably want to it via a Flight NFS appliance which can use the flight trigger functionality to get the stuff to happen

**Comment by mjtko** [comment]
Ok, ta. Will close this as wontfix for now, we can reopen later if we change our minds.
