### ISSUE TITLE
Store a 'clusterware users' personality

### ISSUE THREAD

**Issue by sierra-tango-echo** [alces-software/clusterware#92]
To cope better with ephemeral clusters we could be looking at users personal config being stored in the cloud, mainly of interest at the moment is for a cluster to spin up with a users s3 keys etc already installed so that Alces storage immediately works. going forward features could include storing frequently run job scripts etc

maybe this could be as a pack obtained from a secure service or maybe we store entire users home dirs in s3 and sync that at boot.

open to ideas 🙂

**Comment by mjtko** [comment]
From my research, it looks like the minimal friction approach is to grant an IAM role to the instance with appropriate S3 access.  As an example:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1462268532000",
            "Effect": "Allow",
            "Action": [
                "s3:DeleteObject",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3::::aa11bb22-username.alces-flight.com",
                "arn:aws:s3::::aa11bb22-username.alces-flight.com/*"
            ]
        }
    ]
}
```

Then we can use s3cmd to orchestrate the synchronization using a config file like this:

```
[default]
access_key =
secret_key =
security_token =
```

I envisage a tool that does something like:

Inwards:
1. s3cmd sync in from s3 bucket to home directory
2. use `.config/clusterware/homesync.yml` to update ownerships/modes

Outwards:
1. create/update `.config/clusterware/homesync.yml` with ownerships/modes
2. s3cmd sync out home directory to s3 bucket

`homesync.yml` could also list paths to exclude as well as which bucket to use.  I’d imagine the tool to provide an easy way to add paths to be excluded.  It may be better (for some? all? users) to allow this to be inverted and insist on users opting in to certain paths being stored.

As a fallback, if there is no IAM role defined on the instance, we would need the user to supply their access key and secret.  This can probably be detected at runtime and prompted for (either interactively or as part of the login banner) at first login.

**Comment by mjtko** [comment]
Part of alces-software/flight-aws-marketplace#14
