### ISSUE TITLE
Gridware dependencies - error when dependencies aren't available

### ISSUE THREAD

**Issue by RuanEllis** [alces-software/clusterware#96]
Gridware will fail when there is an error of a package not being installed (namely when a package isn't available) - you get:
`Dependencies ... error: undefined method 'reject' for nil:NilClass. Use --trace to view backtrace`

**Comment by mjtko** [comment]
Analysis shows that this is caused when stderr on any failed script is less than 10 lines long.  Guess that’s been a rare occurrence up until now!
